# Generated by Django 3.1.2 on 2020-11-08 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Favorite_Naruto_Character',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
